### ISSUE TITLE
NetworkLevel

### ISSUE THREAD

**Issue by InkoHX** [VectorNetworkProject/UserdataProvider#22]
# テーブルの中身
```
テーブルの名前: networklevel
exp int
```

**Comment by UramnOIL** [comment]
NetworkLevelはそれぞれのexpをまとめたものという認識で大丈夫ですか？

**Comment by InkoHX** [comment]
それで大丈夫です。

**Comment by UramnOIL** [comment]
完了しました。それと変更ついでにTableManagerにregister()とunregister()を作っておきました。プレイヤーが初参加した場合などに使用してください
